
Description: Security groups with basic Ingress and Egress rule.

Parameters:
  MyVpc:
    Type: <AWS::EC2::VPC::Id>
    
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For allowing any Traffic 
      VpcId: !Ref MyVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 192.168.0.0/24
      SecurityGroupEgress:
        - IpProtocol: tcp 
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/26

 