apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
  name: nodejs-cluster
  region: ap-southeast-2

nodeGroups: 
  - name: test-node
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: false
