Description: This Templates creates DynamoDBTable  with Cloudwatch alarm when read capacity units crosses 90% for continuous 15 seconds.

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: My-table
      BackupRetentionPeriod: 7
      SSESpecification:
        SSEEnabled: true
        SSEType: AES256 

  DynamoDBBackup:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTable
      BackupName: My-backup
      
  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: DynamoDB table example-table has exceeded 90% of provisioned capacity
      Namespace: AWS/DynamoDB
      MetricName: ConsumedReadCapacityUnits
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 90
      ComparisonOperator: GreaterThanOrEqualToThreshold
