
Parameters: 
  AlarmEmail: 
    Default: sashish0377@gmail.com
    Description: "Email address to notify of operational issues"
    Type: String

  MyfirstQueue:
    Type: String
  
Resources: 
  MyQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref MyfirstQueue
  AlarmTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: 
            Ref: AlarmEmail
          Protocol: email
  QueueDepthAlarm: 
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmDescription: "Alarm if queue depth increases to more than 10 messages"
      Namespace: AWS/SQS
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions: 
        - 
          Name: QueueName
          Value: 
            Fn::GetAtt: 
              - MyQueue
              - QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: 
        - Ref: AlarmTopic
      InsufficientDataActions: 
        - Ref: AlarmTopic